name: Python application

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        pytest -v
    - name: Deploy to PythonAnywhere
      # env:
      #   HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
      #   HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
      # if: github.ref == 'refs/heads/main' && job.status == 'success'
      run: |
        mkdir -p ~/.ssh
        touch ~/.ssh/id_rsa
        echo "${{ secrets.PYTHONANYWHERE }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh kartikyanigar@ssh.pythonanywhere.com
        cd lsh
        git


      

